copyright: Copyright 2018 Tyler Trussell All Rights Reserved
docs_dir: docs_src
extra_css:
- extras.css
pages:
- Home: index.md
- docgen-api:
  - catnado:
    - __init__: docgen-api/catnado.md
    - handlers:
      - __init__: docgen-api/catnado.handlers.md
      - csrf_protected_handler: docgen-api/catnado.handlers.csrf_protected_handler.md
      - service_api_handler: docgen-api/catnado.handlers.service_api_handler.md
      - simple_public_handler: docgen-api/catnado.handlers.simple_public_handler.md
      - test:
        - __init__: docgen-api/catnado.handlers.test.md
        - test_csrf_protected_handler: docgen-api/catnado.handlers.test.test_csrf_protected_handler.md
        - test_service_api_handler: docgen-api/catnado.handlers.test.test_service_api_handler.md
    - properties:
      - __init__: docgen-api/catnado.properties.md
      - choice_property: docgen-api/catnado.properties.choice_property.md
      - decimal_property: docgen-api/catnado.properties.decimal_property.md
      - derived_property: docgen-api/catnado.properties.derived_property.md
      - immutabe_property: docgen-api/catnado.properties.immutabe_property.md
      - json_property: docgen-api/catnado.properties.json_property.md
      - key_property: docgen-api/catnado.properties.key_property.md
      - pickle_property: docgen-api/catnado.properties.pickle_property.md
      - test:
        - __init__: docgen-api/catnado.properties.test.md
        - data:
          - __init__: docgen-api/catnado.properties.test.data.md
          - json_data: docgen-api/catnado.properties.test.data.json_data.md
          - json_schemas: docgen-api/catnado.properties.test.data.json_schemas.md
        - test_decimal_property: docgen-api/catnado.properties.test.test_decimal_property.md
        - test_immutable_property: docgen-api/catnado.properties.test.test_immutable_property.md
        - test_imports: docgen-api/catnado.properties.test.test_imports.md
        - test_json_property: docgen-api/catnado.properties.test.test_json_property.md
        - test_key_property: docgen-api/catnado.properties.test.test_key_property.md
        - testcase: docgen-api/catnado.properties.test.testcase.md
      - transform_property: docgen-api/catnado.properties.transform_property.md
      - translatable_property: docgen-api/catnado.properties.translatable_property.md
    - testing:
      - __init__: docgen-api/catnado.testing.md
      - app: docgen-api/catnado.testing.app.md
      - testcase: docgen-api/catnado.testing.testcase.md
    - utils:
      - __init__: docgen-api/catnado.utils.md
      - api: docgen-api/catnado.utils.api.md
      - csrf: docgen-api/catnado.utils.csrf.md
      - environment: docgen-api/catnado.utils.environment.md
      - jinja: docgen-api/catnado.utils.jinja.md
      - test:
        - __init__: docgen-api/catnado.utils.test.md
        - test_api: docgen-api/catnado.utils.test.test_api.md
        - test_csrf: docgen-api/catnado.utils.test.test_csrf.md
        - test_validators: docgen-api/catnado.utils.test.test_validators.md
      - validators: docgen-api/catnado.utils.validators.md
    - versionedmodel:
      - __init__: docgen-api/catnado.versionedmodel.md
      - test_versionedmodel: docgen-api/catnado.versionedmodel.test_versionedmodel.md
repo_url: https://github.com/tylertrussell/gae-catnado
site_author: Tyler Trussell
site_description: gae-catnado, a library of helpers for Google App Engine
site_dir: docs
site_name: gae-catnado
site_url: https://tylertrussell.github.io/gae-catnado
theme: material
