site_name: gae-catnado

site_url: https://tylertrussell.github.io/gae-catnado
repo_url: https://github.com/tylertrussell/gae-catnado

docs_dir: docs_src
site_dir: docs

site_description: gae-catnado, a library of helpers for Google App Engine
site_author: Tyler Trussell
copyright: Copyright 2018 Tyler Trussell All Rights Reserved

theme: material

extra_css: [extras.css]

pages:
  - Home: index.md
  - API:
    - catnado.properties:
      - Overview: api/properties/overview.md
      - catnado.properties.key_property: api/properties/key_property.md
    - catnado.versionedmodel:
      - Overview: api/versionedmodel/overview.md
